jobs:
- name: ping
  plan:
  - task: ping
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: "alpine"
      run:
        path: "/bin/ash"
        args:
        - "-c"
        - "echo HELLO $PERSON"
    params:
      PERSON: ((hello))
