version: '3'

services:
  concourse-db:
    image: postgres
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_PASSWORD=concourse_pass
    - POSTGRES_USER=concourse_user
    - PGDATA=/database

  concourse:
    image: concourse/concourse
    command: quickstart
    privileged: true
    depends_on: [concourse-db, registry, minio, git-server, vault]
    ports: ["8080:8080"]
    environment:
    - CONCOURSE_POSTGRES_HOST=concourse-db
    - CONCOURSE_POSTGRES_USER=concourse_user
    - CONCOURSE_POSTGRES_PASSWORD=concourse_pass
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_MAIN_TEAM_ALLOW_ALL_USERS=true
    - CONCOURSE_NO_REALLY_I_DONT_WANT_ANY_AUTH=true
    - CONCOURSE_RESOURCE_CHECKING_INTERVAL=5s
    - CONCOURSE_VAULT_URL=http://vault:8200
    - CONCOURSE_VAULT_CLIENT_TOKEN=35eb29c4-1635-40b6-85fe-3684f8006f86

  registry:
    image: registry:2
    volumes:
      - "registry:/var/lib/registry"
    ports:
      - "5000:5000"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: changeme
    command: server /data

  git-server:
    image: jkarlos/git-server-docker
    volumes:
      - ./keys/ssh:/git-server/keys
      - ./repos:/git-server/repos
    ports: ["22222:22"]

  vault:
    image: vault
    ports: ["8200:8200"]
    environment:
    - VAULT_DEV_ROOT_TOKEN_ID=8568d046-b70a-64f6-ebfe-ec2a891a8ba3

volumes:
  registry:
    external: true
