---
applications:
- name: backend
  buildpack: java_buildpack_offline
  instances: 1
  memory: 768M
  disk_quota: 256M
  routes:
  - route: todo.pcfbeta.io/api
  path: backend/todo.jar

- name: web-app
  buildpack: staticfile_buildpack
  instances: 1
  memory: 256M
  disk_quota: 256M
  routes:
  - route: todo.pcfbeta.io
  path: frontend
